# Generated by Django 4.1.7 on 2023-04-17 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('background', models.TextField(max_length=20)),
                ('job', models.TextField(max_length=20)),
                ('race', models.TextField(max_length=20)),
                ('experience', models.IntegerField()),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration', models.IntegerField()),
                ('proeficiency', models.IntegerField()),
                ('strength_proeficiency', models.IntegerField()),
                ('dexterity_proeficiency', models.IntegerField()),
                ('constituition_proeficiency', models.IntegerField()),
                ('intelligence_proeficiency', models.IntegerField()),
                ('wisdom_proeficiency', models.IntegerField()),
                ('charisma_proeficiency', models.IntegerField()),
                ('athletics_proeficiency', models.BooleanField()),
                ('stunt_proeficiency', models.BooleanField()),
                ('stealth_proeficiency', models.BooleanField()),
                ('sleight_proeficiency', models.BooleanField()),
                ('arcana_proeficiency', models.BooleanField()),
                ('history_proeficiency', models.BooleanField()),
                ('investigation_proeficiency', models.BooleanField()),
                ('medicine_proeficiency', models.BooleanField()),
                ('nature_proeficiency', models.BooleanField()),
                ('religion_proeficiency', models.BooleanField()),
                ('acting_proeficiency', models.BooleanField()),
                ('bluff_proeficiency', models.BooleanField()),
                ('intimidation_proeficiency', models.BooleanField()),
                ('intuition_proeficiency', models.BooleanField()),
                ('persuasion_proeficiency', models.BooleanField()),
                ('animal_proeficiency', models.BooleanField()),
                ('perception_proeficiency', models.BooleanField()),
                ('survive_proeficiency', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DED_dices.campaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_armor', models.IntegerField()),
                ('iniciative', models.IntegerField()),
                ('displacement', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('language_and_other_skills', models.TextField(max_length=5000)),
                ('pc', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('po', models.IntegerField()),
                ('pl', models.IntegerField()),
                ('da', models.IntegerField()),
                ('ideals', models.TextField(max_length=5000)),
                ('ligations', models.TextField(max_length=5000)),
                ('defects', models.TextField(max_length=5000)),
                ('characteristics_and_skills', models.TextField(max_length=5000)),
                ('appaerance', models.TextField(max_length=5000)),
                ('other_characteristics', models.TextField(max_length=5000)),
                ('allies_and_organizations', models.TextField(max_length=5000)),
                ('inventory', models.TextField(max_length=5000)),
                ('history', models.TextField(max_length=50000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('dices', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('attribute', models.TextField(choices=[('Nenhum', 'Nenhum'), ('Força', 'Força'), ('Destreza', 'Destreza'), ('Constituição', 'Constituição'), ('Inteligência', 'Inteligência'), ('Sabedoria', 'Sabedoria'), ('Carisma', 'Carisma')], max_length=12)),
                ('type', models.TextField(choices=[('Physical', 'Físico'), ('Magic', 'Mágico')], max_length=8)),
                ('proeficiency', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character')),
            ],
        ),
        migrations.CreateModel(
            name='Atributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('strength_proficiency', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('dexterity_proficiency', models.IntegerField()),
                ('constituition', models.IntegerField()),
                ('constituition_proficiency', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('intelligence_proficiency', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('wisdom_proficiency', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('charisma_proficiency', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character')),
            ],
        ),
    ]
