# Generated by Django 4.1.7 on 2023-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='attribute',
            new_name='attribute_modifier',
        ),
        migrations.RenameField(
            model_name='attack',
            old_name='dices',
            new_name='dice_1',
        ),
        migrations.AddField(
            model_name='attack',
            name='damage_modifier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='dice_2',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='dice_3',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='magic_lvl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='rool_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='rool_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='rool_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
