# Generated by Django 4.1.7 on 2023-04-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0003_character_lvl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributes',
            old_name='charisma',
            new_name='charisma_atribute',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='constituition',
            new_name='charisma_modifier',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='charisma_proficiency',
            new_name='constituition_atribute',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='constituition_proficiency',
            new_name='constituition_modifier',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='dexterity',
            new_name='dexterity_atribute',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='dexterity_proficiency',
            new_name='dexterity_modifier',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='intelligence',
            new_name='intelligence_atribute',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='intelligence_proficiency',
            new_name='intelligence_modifier',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='strength',
            new_name='strength_atribute',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='strength_proficiency',
            new_name='strength_modifier',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='wisdom',
            new_name='wisdom_atribute',
        ),
        migrations.RenameField(
            model_name='atributes',
            old_name='wisdom_proficiency',
            new_name='wisdom_modifier',
        ),
    ]
