# Generated by Django 4.1.7 on 2023-04-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0005_alter_skills_acting_proeficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='da',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='pc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='pl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='pp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
