# Generated by Django 4.1.7 on 2023-04-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0007_alter_attack_damage_modifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='charisma_proeficiency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='constituition_proeficiency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='dexterity_proeficiency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='intelligence_proeficiency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='strength_proeficiency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='wisdom_proeficiency',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
