# Generated by Django 4.1.7 on 2023-04-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0008_alter_skills_charisma_proeficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='inspiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='proeficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
