# Generated by Django 4.1.7 on 2023-04-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0009_alter_character_experience_alter_skills_inspiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='rool_1',
            new_name='roll_1',
        ),
        migrations.RenameField(
            model_name='attack',
            old_name='rool_2',
            new_name='roll_2',
        ),
        migrations.RenameField(
            model_name='attack',
            old_name='rool_3',
            new_name='roll_3',
        ),
    ]
