# Generated by Django 4.1.7 on 2023-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0010_rename_rool_1_attack_roll_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attribute_modifier',
            field=models.TextField(blank=True, choices=[('Nenhum', 'Nenhum'), ('Força', 'Força'), ('Destreza', 'Destreza'), ('Constituição', 'Constituição'), ('Inteligência', 'Inteligência'), ('Sabedoria', 'Sabedoria'), ('Carisma', 'Carisma')], max_length=12, null=True),
        ),
    ]
