# Generated by Django 4.1.7 on 2023-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0011_alter_attack_attribute_modifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='proeficiency',
            new_name='proficiency',
        ),
        migrations.AlterField(
            model_name='attack',
            name='magic_lvl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
