# Generated by Django 4.1.7 on 2023-04-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0012_rename_proeficiency_attack_proficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attribute_modifier',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='type',
            field=models.CharField(max_length=8),
        ),
    ]
