# Generated by Django 4.1.7 on 2023-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0014_alter_attack_magic_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='equipments',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
