# Generated by Django 4.1.7 on 2023-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0015_characteristics_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='class_armor_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='displacement_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='hp_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
