# Generated by Django 4.1.7 on 2023-05-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0016_characteristics_class_armor_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='hp_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
