# Generated by Django 4.1.7 on 2023-05-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0018_alter_attack_attribute_modifier_alter_attack_dice_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attribute_modifier',
            field=models.TextField(default='Nenhum', max_length=12),
        ),
    ]
