# Generated by Django 4.1.7 on 2023-05-21 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0019_alter_attack_attribute_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributes',
            name='charisma_atribute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='charisma_modifier',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='constituition_atribute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='constituition_modifier',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='dexterity_atribute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='dexterity_modifier',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='intelligence_atribute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='intelligence_modifier',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='strength_atribute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='strength_modifier',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='wisdom_atribute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='wisdom_modifier',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='attack',
            name='attribute_modifier',
            field=models.TextField(blank=True, default='Nenhum', max_length=12),
        ),
        migrations.AlterField(
            model_name='attack',
            name='damage_modifier',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='attack',
            name='dice_1',
            field=models.CharField(blank=True, default='Nenhum', max_length=10),
        ),
        migrations.AlterField(
            model_name='attack',
            name='dice_2',
            field=models.CharField(blank=True, default='Nenhum', max_length=10),
        ),
        migrations.AlterField(
            model_name='attack',
            name='dice_3',
            field=models.CharField(blank=True, default='Nenhum', max_length=10),
        ),
        migrations.AlterField(
            model_name='attack',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attack',
            name='roll_1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='attack',
            name='roll_2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='attack',
            name='roll_3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='class_armor',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='da',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='displacement',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='hp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='hp_max',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='iniciative',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='pc',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='pl',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='po',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='pp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='skills',
            name='inspiration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skills',
            name='proeficiency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
