# Generated by Django 4.1.7 on 2023-06-09 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DED_dices', '0020_alter_atributes_charisma_atribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='team',
            field=models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
