# Generated by Django 4.1.7 on 2023-06-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0021_campaign_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
