# Generated by Django 4.1.7 on 2023-06-13 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DED_dices', '0023_campaign_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
