# Generated by Django 4.1.7 on 2023-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0024_alter_campaign_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='is_private',
            new_name='chat_private',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_cover/'),
        ),
    ]
