# Generated by Django 4.1.7 on 2023-06-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0025_rename_is_private_campaign_chat_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='campaign_alocated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DED_dices.campaign'),
        ),
    ]
