# Generated by Django 4.1.7 on 2023-06-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0026_character_campaign_alocated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='campaign_alocated',
            new_name='alocated_campaign',
        ),
    ]
