# Generated by Django 4.1.7 on 2023-06-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0027_rename_campaign_alocated_character_alocated_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='alocated_campaign',
            new_name='allocated_campaign',
        ),
    ]
