# Generated by Django 4.1.7 on 2023-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0029_alter_campaign_team_alter_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
