# Generated by Django 4.1.7 on 2023-06-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0031_atributes_created_at_attack_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character'),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DED_dices.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='atributes',
            name='entity_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
        migrations.AddField(
            model_name='attack',
            name='entity_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='entity_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
        migrations.AddField(
            model_name='skills',
            name='entity_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
    ]
