# Generated by Django 4.1.7 on 2023-06-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0032_alter_characteristics_owner_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributes',
            name='entity_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
        migrations.AlterField(
            model_name='atributes',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='entity_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='entity_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character'),
        ),
        migrations.AlterField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.campaign'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='entity_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.character'),
        ),
    ]
