# Generated by Django 4.1.7 on 2023-06-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0033_alter_atributes_entity_owner_alter_atributes_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='entity_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DED_dices.entity'),
        ),
    ]
