# Generated by Django 4.1.7 on 2023-06-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DED_dices', '0034_message_entity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='history',
            field=models.TextField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='notes',
            field=models.TextField(blank=True, max_length=99999999, null=True),
        ),
    ]
